apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-resource-manager
rules:
- apiGroups: ["hyperspike.io"]
  resources: ["valkeys"]
  verbs: ["*"]
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["clusters"]
  verbs: ["*"]
- apiGroups: ["cert-manager.io"]
  resources: ["issuers", "certificates"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-resource-manager-binding
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: crossplane-resource-manager
  apiGroup: rbac.authorization.k8s.io
